# Sniperkit-Bot
# - Date: 2018-08-12 11:57:50.861340307 +0200 CEST m=+0.186538184
# - Status: analyzed

version: '3.3'

services:
  lookout:
    image: "srcd/lookout:latest"
    network_mode: "host"
    depends_on:
      - postgres
      - dummy
    environment:
      GITHUB_USER: ${GITHUB_USER}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "10301:10301"
    entrypoint: ["/bin/sh"]
    # sleep because container with db is up but the db itself doesn't accept connections yet
    command: ["-c", "sleep 5 && lookout migrate && lookout serve ${REPO}"]
    volumes:
      - ./config.yml:/config.yml
  dummy:
    image: "smacker/dummy-analyzer:latest"
    network_mode: "host"
    ports:
      - "10302:10302"
  bblfsh:
    image: "bblfsh/bblfshd:v2.5.0"
    privileged: true
    ports:
      - "9432:9432"
    volumes:
      - type: volume
        source: drivers
        target: /var/lib/bblfshd
    entrypoint: ["/bin/sh"]
    command:
    - "-c"
    - "bblfshd & sleep 1 && bblfshctl driver install --recommended && tail -f /dev/null"
  postgres:
    image: "postgres:alpine"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: lookout
volumes:
  drivers:
